<a href="https://colab.research.google.com/github/maryreginaf15/AnaliseDeDaDosComIA/blob/main/AnaliseDescritiva.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [4]:
#importacao de dados


#df_vendas1 = pd.read_csv("/content/base_dados_vendas_tratada.csv")
#df_vendas2 = pd.read_csv("/content/dados_complementares.csv")
#df_metas = pd.read_excel("/content/Python_JOIN_Metas.xlsx")
df_vendas1 = pd.read_csv("/content/base_dados_vendas_tratada.csv",parse_dates = ['dt_venda', 'dt_entrega'])
df_vendas2 = pd.read_csv("/content/dados_complementares.csv",parse_dates = ['dt_venda', 'dt_entrega'])
df_metas = pd.read_excel("/content/Python_JOIN_Metas.xlsx")

In [5]:

df_vendas1.head()

,dt_venda,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final
0,2020-08-25 10:04:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,3,2020-08-31 16:39:00,1212.3
1,2020-06-10 15:34:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10011,Liquidificador,Cozinha,59.9,142.4,2,2020-06-11 13:59:00,284.8
2,2019-03-21 15:58:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,2,2019-03-28 09:44:00,808.2
3,2019-09-16 14:46:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,2,2019-09-20 09:22:00,3418.2
4,2019-11-25 16:28:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10005,Notebook,Eletrônicos,2299.9,3199.0,2,2019-11-26 13:42:00,6398.0

In [6]:
df_vendas2.head()

,dt_venda,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final
0,2020-03-20,123456111,José Maria,Vendedor,CL001,Loja Matriz,10006,Aspirador de pó,Casa,88.9,189.9,4,2019-03-29 16:37:00,759.6
1,2019-12-22,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10014,Geladeira,Eletrodomésticos,699.9,1346.9,3,2020-07-23 10:54:00,4040.7
2,2019-12-18,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,3,2020-09-04 10:50:00,287.7
3,2019-09-02,123456444,Ricardo Lemos,Vendedor,CL002,Filial MG,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,1,2019-03-28 09:36:00,1709.1
4,2019-01-15,123456222,Maria das Graças,Vendedor,CL001,Loja Matriz,10009,Ferro de passar,Casa,27.9,55.9,3,2020-02-04 15:50:00,167.7

In [7]:
df_metas.head()

    ano  mes    meta
0  2019    1  285000
1  2019    2  285000
2  2019    3  285000
3  2019    4  285000
4  2019    5  285000

In [8]:
df_vendas1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   dt_venda               3000 non-null   datetime64[ns]
 1   matricula_funcionario  3000 non-null   int64
 2   nome_funcionario       3000 non-null   object
 3   cargo                  3000 non-null   object
 4   codigo_loja            3000 non-null   object
 5   nome_loja              3000 non-null   object
 6   codigo_produto         3000 non-null   int64
 7   descricao_produto      3000 non-null   object
 8   categoria              3000 non-null   object
 9   preco_custo            3000 non-null   float64
 10  valor_unitario         3000 non-null   float64
 11  quantidade             3000 non-null   int64
 12  dt_entrega             3000 non-null   datetime64[ns]
 13  valor_final            3000 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(6)
memory usage: 328.3+ KB

In [9]:
df_vendas1[['preco_custo','valor_unitario','quantidade','valor_final']].describe().round(2)

       preco_custo  valor_unitario  quantidade  valor_final
count      3000.00         3000.00     3000.00      3000.00
mean        545.51          926.94        2.45      2234.95
std         563.13          841.84        1.11      2449.47
min          27.90           55.90        1.00        55.90
25%         109.90          189.90        1.00       427.20
50%         210.90          404.10        2.00      1346.90
75%         799.00         1424.91        3.00      3353.80
max        2299.90         3199.00        4.00     12796.00

In [10]:
df_vendas2[['preco_custo','valor_unitario','quantidade','valor_final']].describe().round(2)

       preco_custo  valor_unitario  quantidade  valor_final
count       500.00          500.00      500.00       500.00
mean        550.18          925.93        2.52      2248.96
std         581.42          861.32        1.12      2427.84
min          27.90           55.90        1.00        55.90
25%         110.00          249.90        1.00       499.80
50%         210.90          404.10        3.00      1139.60
75%         899.90         1676.90        3.00      3418.20
max        2299.90         3199.00        4.00     12796.00

In [11]:
df_metas.describe()

               ano        mes      meta
count    24.000000  24.000000      24.0
mean   2019.500000   6.500000  285000.0
std       0.510754   3.526299       0.0
min    2019.000000   1.000000  285000.0
25%    2019.000000   3.750000  285000.0
50%    2019.500000   6.500000  285000.0
75%    2020.000000   9.250000  285000.0
max    2020.000000  12.000000  285000.0

In [12]:
#juncao do dados
#concatenar

df_vendas = pd.concat([df_vendas1,df_vendas2], axis=0, join='outer' )#
df_vendas.head()

,dt_venda,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final
0,2020-08-25 10:04:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,3,2020-08-31 16:39:00,1212.3
1,2020-06-10 15:34:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10011,Liquidificador,Cozinha,59.9,142.4,2,2020-06-11 13:59:00,284.8
2,2019-03-21 15:58:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,2,2019-03-28 09:44:00,808.2
3,2019-09-16 14:46:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,2,2019-09-20 09:22:00,3418.2
4,2019-11-25 16:28:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10005,Notebook,Eletrônicos,2299.9,3199.0,2,2019-11-26 13:42:00,6398.0

In [13]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   dt_venda               3500 non-null   datetime64[ns]
 1   matricula_funcionario  3500 non-null   int64
 2   nome_funcionario       3500 non-null   object
 3   cargo                  3500 non-null   object
 4   codigo_loja            3500 non-null   object
 5   nome_loja              3500 non-null   object
 6   codigo_produto         3500 non-null   int64
 7   descricao_produto      3500 non-null   object
 8   categoria              3500 non-null   object
 9   preco_custo            3500 non-null   float64
 10  valor_unitario         3500 non-null   float64
 11  quantidade             3500 non-null   int64
 12  dt_entrega             3500 non-null   datetime64[ns]
 13  valor_final            3500 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(6)
memory usage: 410.2+ KB

In [14]:
display(df_vendas)

,dt_venda,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final
0,2020-08-25 10:04:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.10,3,2020-08-31 16:39:00,1212.30
1,2020-06-10 15:34:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10011,Liquidificador,Cozinha,59.9,142.40,2,2020-06-11 13:59:00,284.80
2,2019-03-21 15:58:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.10,2,2019-03-28 09:44:00,808.20
3,2019-09-16 14:46:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.10,2,2019-09-20 09:22:00,3418.20
4,2019-11-25 16:28:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10005,Notebook,Eletrônicos,2299.9,3199.00,2,2019-11-26 13:42:00,6398.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,2019-09-04 00:00:00,123457111,Pamela Lima,Vendedor,CL004,Filial ES,10018,Colchão,Casa,109.9,249.90,3,2019-04-12 09:04:00,749.70
496,2020-05-02 00:00:00,123456111,José Maria,Vendedor,CL001,Loja Matriz,10017,Cama Box,Casa,1189.9,1899.50,3,2020-03-11 10:27:00,5698.50
497,2020-06-14 00:00:00,123456333,Jorge Mateus,Vendedor,CL001,Loja Matriz,10003,Televisão,Eletrodomésticos,1400.9,2279.99,1,2019-04-07 15:45:00,2279.99
498,2020-11-04 00:00:00,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.10,3,2019-11-05 15:44:00,5127.30
499,2019-07-26 00:00:00,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10013,Fogão,Eletrodomésticos,210.9,404.10,1,2019-02-25 14:14:00,404.10

In [15]:
df_vendas.duplicated().sum()

np.int64(0)

In [16]:
#mesclagem

df_vendas['mes'] = df_vendas['dt_venda'].dt.month
df_vendas['ano'] = df_vendas['dt_venda'].dt.year

In [17]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3500 entries, 0 to 499
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   dt_venda               3500 non-null   datetime64[ns]
 1   matricula_funcionario  3500 non-null   int64
 2   nome_funcionario       3500 non-null   object
 3   cargo                  3500 non-null   object
 4   codigo_loja            3500 non-null   object
 5   nome_loja              3500 non-null   object
 6   codigo_produto         3500 non-null   int64
 7   descricao_produto      3500 non-null   object
 8   categoria              3500 non-null   object
 9   preco_custo            3500 non-null   float64
 10  valor_unitario         3500 non-null   float64
 11  quantidade             3500 non-null   int64
 12  dt_entrega             3500 non-null   datetime64[ns]
 13  valor_final            3500 non-null   float64
 14  mes                    3500 non-null   int32
 15  ano                    3500 non-null   int32
dtypes: datetime64[ns](2), float64(3), int32(2), int64(3), object(6)
memory usage: 437.5+ KB

In [18]:
df_final = df_vendas.merge(df_metas, on=['ano', 'mes'],how='inner')

In [19]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   dt_venda               3500 non-null   datetime64[ns]
 1   matricula_funcionario  3500 non-null   int64
 2   nome_funcionario       3500 non-null   object
 3   cargo                  3500 non-null   object
 4   codigo_loja            3500 non-null   object
 5   nome_loja              3500 non-null   object
 6   codigo_produto         3500 non-null   int64
 7   descricao_produto      3500 non-null   object
 8   categoria              3500 non-null   object
 9   preco_custo            3500 non-null   float64
 10  valor_unitario         3500 non-null   float64
 11  quantidade             3500 non-null   int64
 12  dt_entrega             3500 non-null   datetime64[ns]
 13  valor_final            3500 non-null   float64
 14  mes                    3500 non-null   int32
 15  ano                    3500 non-null   int32
 16  meta                   3500 non-null   int64
dtypes: datetime64[ns](2), float64(3), int32(2), int64(4), object(6)
memory usage: 437.6+ KB

In [20]:
df_final['lucro'] = (df_final['valor_unitario'] - df_final['preco_custo']) * df_final['quantidade']
df_final['margem_lucro'] = (df_final['valor_unitario'] - df_final['preco_custo']) / df_final['valor_unitario']
df_final['prazo_entrega'] = df_final['dt_entrega'] - df_final['dt_venda']
df_final['valor_final'] = df_final['valor_unitario'] * df_final['quantidade']

In [21]:
df_final.drop(columns=['matricula_funcionario','codigo_produto','codigo_loja'],inplace=True)

In [22]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   dt_venda           3500 non-null   datetime64[ns]
 1   nome_funcionario   3500 non-null   object
 2   cargo              3500 non-null   object
 3   nome_loja          3500 non-null   object
 4   descricao_produto  3500 non-null   object
 5   categoria          3500 non-null   object
 6   preco_custo        3500 non-null   float64
 7   valor_unitario     3500 non-null   float64
 8   quantidade         3500 non-null   int64
 9   dt_entrega         3500 non-null   datetime64[ns]
 10  valor_final        3500 non-null   float64
 11  mes                3500 non-null   int32
 12  ano                3500 non-null   int32
 13  meta               3500 non-null   int64
 14  lucro              3500 non-null   float64
 15  margem_lucro       3500 non-null   float64
 16  prazo_entrega      3500 non-null   timedelta64[ns]
dtypes: datetime64[ns](2), float64(5), int32(2), int64(2), object(5), timedelta64[ns](1)
memory usage: 437.6+ KB

In [23]:
#salvando a base

df_final.to_csv("/content/base_dados_tratada.csv")

In [24]:
#analise descritiva

#fiLTROS LOGICO DE DADOS

# > MAIOR QUE
# < MENOR QIE
# >= MAIOR OU IGUAL QUE
#<= MENOR OU IGUAL QUE
# == IGUAL A
# != DIFERENTE DE
# & (E)
# | (OU )
# ~ (NÃO )
#
#
#

In [25]:
df_final.describe(include='object')

        nome_funcionario     cargo    nome_loja descricao_produto categoria
count               3500      3500         3500              3500      3500
unique                12         1            4                20         4
top     Maria das Graças  Vendedor  Loja Matriz        Microondas      Casa
freq                 325      3500          940               203      1050

In [26]:
df_final.nome_loja.unique()

array(['Filial SP', 'Loja Matriz', 'Filial MG', 'Filial ES'], dtype=object)

In [27]:
df_final.nome_funcionario.unique()

array(['Felipe Marinho', 'Jorge Mateus', 'José Maria', 'Marcos Coelho',
       'Maria das Graças', 'Marta Cury', 'Mário Henrique', 'Pamela Lima',
       'Reginaldo Sodré', 'Ricardo Lemos', 'Rita Sampaio', 'Victor Hugo'],
      dtype=object)

In [28]:
df_final.descricao_produto.unique()

array(['Fogão', 'Liquidificador', 'Máquina Lavar Roupa', 'Notebook',
       'Colchão', 'Fritadeira elétrica', 'Televisão', 'Sofá',
       'Processador de alimentos', 'Ferro de passar', 'Guarda Roupa',
       'Tablet', 'Aspirador de pó', 'Geladeira', 'Smartphone',
       'Microondas', 'Cafeteira', 'Batedeira', 'Impressora', 'Cama Box'],
      dtype=object)

In [29]:
#criando um  filtro #queries consultas

filtro_loja = df_final['nome_loja'] == 'Loja Matriz'
df_final[filtro_loja]

,dt_venda,nome_funcionario,cargo,nome_loja,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,mes,ano,meta,lucro,margem_lucro,prazo_entrega
261,2020-02-25 16:58:00,Jorge Mateus,Vendedor,Loja Matriz,Colchão,Casa,109.9,249.90,2,2020-02-26 14:58:00,499.80,2,2020,285000,280.00,0.560224,0 days 22:00:00
262,2019-09-20 13:24:00,Jorge Mateus,Vendedor,Loja Matriz,Liquidificador,Cozinha,59.9,142.40,2,2019-09-21 11:12:00,284.80,9,2019,285000,165.00,0.579354,0 days 21:48:00
263,2020-05-04 15:25:00,Jorge Mateus,Vendedor,Loja Matriz,Colchão,Casa,109.9,249.90,2,2020-05-04 17:00:00,499.80,5,2020,285000,280.00,0.560224,0 days 01:35:00
264,2019-08-14 11:51:00,Jorge Mateus,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,2,2019-08-14 12:02:00,6398.00,8,2019,285000,1798.20,0.281057,0 days 00:11:00
265,2020-03-21 11:56:00,Jorge Mateus,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,2,2020-03-22 10:54:00,6398.00,3,2020,285000,1798.20,0.281057,0 days 22:58:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3493,2019-02-23 00:00:00,Jorge Mateus,Vendedor,Loja Matriz,Televisão,Eletrodomésticos,1400.9,2279.99,4,2020-05-09 11:36:00,9119.96,2,2019,285000,3516.36,0.385567,441 days 11:36:00
3494,2019-12-13 00:00:00,José Maria,Vendedor,Loja Matriz,Cafeteira,Cozinha,159.9,284.90,1,2020-09-24 15:31:00,284.90,12,2019,285000,125.00,0.438750,286 days 15:31:00
3496,2020-05-02 00:00:00,José Maria,Vendedor,Loja Matriz,Cama Box,Casa,1189.9,1899.50,3,2020-03-11 10:27:00,5698.50,5,2020,285000,2128.80,0.373572,-52 days +10:27:00
3497,2020-06-14 00:00:00,Jorge Mateus,Vendedor,Loja Matriz,Televisão,Eletrodomésticos,1400.9,2279.99,1,2019-04-07 15:45:00,2279.99,6,2020,285000,879.09,0.385567,-434 days +15:45:00
3498,2020-11-04 00:00:00,José Maria,Vendedor,Loja Matriz,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.10,3,2019-11-05 15:44:00,5127.30,11,2020,285000,1830.30,0.356972,-365 days +15:44:00

In [30]:
filtro_fatura = df_final['valor_final'] > 8000
df_final[filtro_fatura]

,dt_venda,nome_funcionario,cargo,nome_loja,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,mes,ano,meta,lucro,margem_lucro,prazo_entrega
109,2019-01-21 17:42:00,Felipe Marinho,Vendedor,Filial SP,Notebook,Eletrônicos,2299.9,3199.00,3,2019-01-22 13:50:00,9597.00,1,2019,285000,2697.30,0.281057,0 days 20:08:00
142,2019-05-01 09:56:00,Felipe Marinho,Vendedor,Filial SP,Notebook,Eletrônicos,2299.9,3199.00,4,2019-05-02 09:52:00,12796.00,5,2019,285000,3596.40,0.281057,0 days 23:56:00
192,2019-01-24 15:41:00,Felipe Marinho,Vendedor,Filial SP,Televisão,Eletrodomésticos,1400.9,2279.99,4,2019-01-26 17:23:00,9119.96,1,2019,285000,3516.36,0.385567,2 days 01:42:00
197,2020-09-04 10:55:00,Felipe Marinho,Vendedor,Filial SP,Televisão,Eletrodomésticos,1400.9,2279.99,4,2020-09-11 10:41:00,9119.96,9,2020,285000,3516.36,0.385567,6 days 23:46:00
238,2019-04-03 12:30:00,Felipe Marinho,Vendedor,Filial SP,Televisão,Eletrodomésticos,1400.9,2279.99,4,2019-04-07 15:33:00,9119.96,4,2019,285000,3516.36,0.385567,4 days 03:03:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3282,2019-09-15 00:00:00,José Maria,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2020-08-07 14:53:00,9597.00,9,2019,285000,2697.30,0.281057,327 days 14:53:00
3313,2020-11-30 00:00:00,Marcos Coelho,Vendedor,Filial SP,Notebook,Eletrônicos,2299.9,3199.00,3,2019-03-25 11:47:00,9597.00,11,2020,285000,2697.30,0.281057,-616 days +11:47:00
3402,2020-03-15 00:00:00,Ricardo Lemos,Vendedor,Filial MG,Televisão,Eletrodomésticos,1400.9,2279.99,4,2019-11-01 14:31:00,9119.96,3,2020,285000,3516.36,0.385567,-135 days +14:31:00
3445,2020-03-01 00:00:00,Pamela Lima,Vendedor,Filial ES,Televisão,Eletrodomésticos,1400.9,2279.99,4,2020-12-05 14:38:00,9119.96,3,2020,285000,3516.36,0.385567,279 days 14:38:00
3493,2019-02-23 00:00:00,Jorge Mateus,Vendedor,Loja Matriz,Televisão,Eletrodomésticos,1400.9,2279.99,4,2020-05-09 11:36:00,9119.96,2,2019,285000,3516.36,0.385567,441 days 11:36:00

In [31]:
df_final[filtro_loja& filtro_fatura]

,dt_venda,nome_funcionario,cargo,nome_loja,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,mes,ano,meta,lucro,margem_lucro,prazo_entrega
357,2019-04-27 14:26:00,Jorge Mateus,Vendedor,Loja Matriz,Televisão,Eletrodomésticos,1400.9,2279.99,4,2019-04-29 16:38:00,9119.96,4,2019,285000,3516.36,0.385567,2 days 02:12:00
369,2020-05-03 15:31:00,Jorge Mateus,Vendedor,Loja Matriz,Televisão,Eletrodomésticos,1400.9,2279.99,4,2020-05-09 11:36:00,9119.96,5,2020,285000,3516.36,0.385567,5 days 20:05:00
373,2020-06-08 16:42:00,Jorge Mateus,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2020-06-09 12:09:00,9597.00,6,2020,285000,2697.30,0.281057,0 days 19:27:00
391,2019-03-09 17:30:00,Jorge Mateus,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,4,2019-03-10 17:07:00,12796.00,3,2019,285000,3596.40,0.281057,0 days 23:37:00
392,2020-09-02 13:14:00,Jorge Mateus,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,4,2020-09-02 17:08:00,12796.00,9,2020,285000,3596.40,0.281057,0 days 03:54:00
401,2020-10-04 14:18:00,Jorge Mateus,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2020-10-05 12:12:00,9597.00,10,2020,285000,2697.30,0.281057,0 days 21:54:00
404,2019-08-22 14:30:00,Jorge Mateus,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,4,2019-08-23 10:33:00,12796.00,8,2019,285000,3596.40,0.281057,0 days 20:03:00
414,2019-05-19 13:15:00,Jorge Mateus,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2019-05-19 17:50:00,9597.00,5,2019,285000,2697.30,0.281057,0 days 04:35:00
423,2019-01-29 15:38:00,Jorge Mateus,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2019-01-30 12:23:00,9597.00,1,2019,285000,2697.30,0.281057,0 days 20:45:00
425,2019-06-18 14:34:00,Jorge Mateus,Vendedor,Loja Matriz,Televisão,Eletrodomésticos,1400.9,2279.99,4,2019-06-24 15:09:00,9119.96,6,2019,285000,3516.36,0.385567,6 days 00:35:00
536,2020-05-17 14:12:00,José Maria,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,4,2020-05-18 11:16:00,12796.00,5,2020,285000,3596.40,0.281057,0 days 21:04:00
537,2020-03-02 13:22:00,José Maria,Vendedor,Loja Matriz,Televisão,Eletrodomésticos,1400.9,2279.99,4,2020-03-06 13:22:00,9119.96,3,2020,285000,3516.36,0.385567,4 days 00:00:00
553,2019-06-03 16:50:00,José Maria,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2019-06-03 17:05:00,9597.00,6,2019,285000,2697.30,0.281057,0 days 00:15:00
563,2020-03-26 11:01:00,José Maria,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2020-03-26 11:04:00,9597.00,3,2020,285000,2697.30,0.281057,0 days 00:03:00
567,2019-02-06 10:06:00,José Maria,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2019-02-07 09:23:00,9597.00,2,2019,285000,2697.30,0.281057,0 days 23:17:00
568,2020-11-07 16:48:00,José Maria,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2020-11-08 12:03:00,9597.00,11,2020,285000,2697.30,0.281057,0 days 19:15:00
577,2020-03-13 15:21:00,José Maria,Vendedor,Loja Matriz,Televisão,Eletrodomésticos,1400.9,2279.99,4,2020-03-17 15:57:00,9119.96,3,2020,285000,3516.36,0.385567,4 days 00:36:00
587,2019-05-20 12:04:00,José Maria,Vendedor,Loja Matriz,Televisão,Eletrodomésticos,1400.9,2279.99,4,2019-05-24 14:36:00,9119.96,5,2019,285000,3516.36,0.385567,4 days 02:32:00
618,2020-02-05 13:11:00,José Maria,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2020-02-06 10:47:00,9597.00,2,2020,285000,2697.30,0.281057,0 days 21:36:00
624,2019-01-22 13:29:00,José Maria,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2019-01-22 17:13:00,9597.00,1,2019,285000,2697.30,0.281057,0 days 03:44:00
744,2020-08-07 13:11:00,José Maria,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2020-08-07 14:53:00,9597.00,8,2020,285000,2697.30,0.281057,0 days 01:42:00
751,2020-12-30 09:05:00,José Maria,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2020-12-30 14:55:00,9597.00,12,2020,285000,2697.30,0.281057,0 days 05:50:00
753,2020-09-01 11:33:00,José Maria,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2020-09-01 13:18:00,9597.00,9,2020,285000,2697.30,0.281057,0 days 01:45:00
1035,2020-02-12 17:56:00,Maria das Graças,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2020-02-13 11:08:00,9597.00,2,2020,285000,2697.30,0.281057,0 days 17:12:00
1057,2020-10-24 17:55:00,Maria das Graças,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2020-10-25 10:02:00,9597.00,10,2020,285000,2697.30,0.281057,0 days 16:07:00
1064,2019-08-18 09:21:00,Maria das Graças,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2019-08-18 11:09:00,9597.00,8,2019,285000,2697.30,0.281057,0 days 01:48:00
1141,2019-08-01 15:29:00,Maria das Graças,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2019-08-01 16:16:00,9597.00,8,2019,285000,2697.30,0.281057,0 days 00:47:00
1160,2019-11-22 13:28:00,Maria das Graças,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2019-11-23 10:07:00,9597.00,11,2019,285000,2697.30,0.281057,0 days 20:39:00
1185,2019-05-29 14:49:00,Maria das Graças,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,4,2019-05-30 14:22:00,12796.00,5,2019,285000,3596.40,0.281057,0 days 23:33:00
1237,2019-08-17 15:28:00,Maria das Graças,Vendedor,Loja Matriz,Televisão,Eletrodomésticos,1400.9,2279.99,4,2019-08-21 16:27:00,9119.96,8,2019,285000,3516.36,0.385567,4 days 00:59:00
1244,2020-02-28 15:45:00,Maria das Graças,Vendedor,Loja Matriz,Televisão,Eletrodomésticos,1400.9,2279.99,4,2020-03-06 09:40:00,9119.96,2,2020,285000,3516.36,0.385567,6 days 17:55:00
1250,2020-06-24 11:04:00,Maria das Graças,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,4,2020-06-24 11:08:00,12796.00,6,2020,285000,3596.40,0.281057,0 days 00:04:00
1272,2019-05-18 13:18:00,Maria das Graças,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,4,2019-05-19 10:21:00,12796.00,5,2019,285000,3596.40,0.281057,0 days 21:03:00
1297,2019-10-15 09:00:00,Maria das Graças,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,4,2019-10-15 12:11:00,12796.00,10,2019,285000,3596.40,0.281057,0 days 03:11:00
3006,2019-04-11 00:00:00,José Maria,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2020-08-07 14:53:00,9597.00,4,2019,285000,2697.30,0.281057,484 days 14:53:00
3022,2020-06-27 00:00:00,Maria das Graças,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2019-08-18 11:09:00,9597.00,6,2020,285000,2697.30,0.281057,-314 days +11:09:00
3064,2020-12-28 00:00:00,Maria das Graças,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2019-11-23 10:07:00,9597.00,12,2020,285000,2697.30,0.281057,-401 days +10:07:00
3068,2020-09-13 00:00:00,Maria das Graças,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2020-02-13 11:08:00,9597.00,9,2020,285000,2697.30,0.281057,-213 days +11:08:00
3165,2019-03-20 00:00:00,José Maria,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2020-03-26 11:04:00,9597.00,3,2019,285000,2697.30,0.281057,372 days 11:04:00
3254,2019-10-12 00:00:00,José Maria,Vendedor,Loja Matriz,Televisão,Eletrodomésticos,1400.9,2279.99,4,2020-03-06 13:22:00,9119.96,10,2019,285000,3516.36,0.385567,146 days 13:22:00
3265,2019-01-15 00:00:00,Jorge Mateus,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,4,2020-09-02 17:08:00,12796.00,1,2019,285000,3596.40,0.281057,596 days 17:08:00
3282,2019-09-15 00:00:00,José Maria,Vendedor,Loja Matriz,Notebook,Eletrônicos,2299.9,3199.00,3,2020-08-07 14:53:00,9597.00,9,2019,285000,2697.30,0.281057,327 days 14:53:00
3493,2019-02-23 00:00:00,Jorge Mateus,Vendedor,Loja Matriz,Televisão,Eletrodomésticos,1400.9,2279.99,4,2020-05-09 11:36:00,9119.96,2,2019,285000,3516.36,0.385567,441 days 11:36:00

In [32]:
df_final[filtro_loja | filtro_fatura]

,dt_venda,nome_funcionario,cargo,nome_loja,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,mes,ano,meta,lucro,margem_lucro,prazo_entrega
109,2019-01-21 17:42:00,Felipe Marinho,Vendedor,Filial SP,Notebook,Eletrônicos,2299.9,3199.00,3,2019-01-22 13:50:00,9597.00,1,2019,285000,2697.30,0.281057,0 days 20:08:00
142,2019-05-01 09:56:00,Felipe Marinho,Vendedor,Filial SP,Notebook,Eletrônicos,2299.9,3199.00,4,2019-05-02 09:52:00,12796.00,5,2019,285000,3596.40,0.281057,0 days 23:56:00
192,2019-01-24 15:41:00,Felipe Marinho,Vendedor,Filial SP,Televisão,Eletrodomésticos,1400.9,2279.99,4,2019-01-26 17:23:00,9119.96,1,2019,285000,3516.36,0.385567,2 days 01:42:00
197,2020-09-04 10:55:00,Felipe Marinho,Vendedor,Filial SP,Televisão,Eletrodomésticos,1400.9,2279.99,4,2020-09-11 10:41:00,9119.96,9,2020,285000,3516.36,0.385567,6 days 23:46:00
238,2019-04-03 12:30:00,Felipe Marinho,Vendedor,Filial SP,Televisão,Eletrodomésticos,1400.9,2279.99,4,2019-04-07 15:33:00,9119.96,4,2019,285000,3516.36,0.385567,4 days 03:03:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3493,2019-02-23 00:00:00,Jorge Mateus,Vendedor,Loja Matriz,Televisão,Eletrodomésticos,1400.9,2279.99,4,2020-05-09 11:36:00,9119.96,2,2019,285000,3516.36,0.385567,441 days 11:36:00
3494,2019-12-13 00:00:00,José Maria,Vendedor,Loja Matriz,Cafeteira,Cozinha,159.9,284.90,1,2020-09-24 15:31:00,284.90,12,2019,285000,125.00,0.438750,286 days 15:31:00
3496,2020-05-02 00:00:00,José Maria,Vendedor,Loja Matriz,Cama Box,Casa,1189.9,1899.50,3,2020-03-11 10:27:00,5698.50,5,2020,285000,2128.80,0.373572,-52 days +10:27:00
3497,2020-06-14 00:00:00,Jorge Mateus,Vendedor,Loja Matriz,Televisão,Eletrodomésticos,1400.9,2279.99,1,2019-04-07 15:45:00,2279.99,6,2020,285000,879.09,0.385567,-434 days +15:45:00
3498,2020-11-04 00:00:00,José Maria,Vendedor,Loja Matriz,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.10,3,2019-11-05 15:44:00,5127.30,11,2020,285000,1830.30,0.356972,-365 days +15:44:00

In [33]:
df_final.query("nome_funcionario == 'Marta Cury'")

,dt_venda,nome_funcionario,cargo,nome_loja,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,mes,ano,meta,lucro,margem_lucro,prazo_entrega
1300,2019-12-23 16:31:00,Marta Cury,Vendedor,Filial MG,Televisão,Eletrodomésticos,1400.9,2279.99,2,2019-12-25 10:27:00,4559.98,12,2019,285000,1758.18,0.385567,1 days 17:56:00
1301,2019-08-30 14:46:00,Marta Cury,Vendedor,Filial MG,Microondas,Eletrodomésticos,189.0,364.50,2,2019-08-31 12:29:00,729.00,8,2019,285000,351.00,0.481481,0 days 21:43:00
1302,2019-11-05 16:53:00,Marta Cury,Vendedor,Filial MG,Geladeira,Eletrodomésticos,699.9,1346.90,2,2019-11-07 14:38:00,2693.80,11,2019,285000,1294.00,0.480362,1 days 21:45:00
1303,2019-06-04 13:40:00,Marta Cury,Vendedor,Filial MG,Notebook,Eletrônicos,2299.9,3199.00,3,2019-06-05 13:07:00,9597.00,6,2019,285000,2697.30,0.281057,0 days 23:27:00
1304,2019-01-03 15:47:00,Marta Cury,Vendedor,Filial MG,Notebook,Eletrônicos,2299.9,3199.00,4,2019-01-04 10:55:00,12796.00,1,2019,285000,3596.40,0.281057,0 days 19:08:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3465,2019-05-07 00:00:00,Marta Cury,Vendedor,Filial MG,Ferro de passar,Casa,27.9,55.90,4,2019-07-29 15:42:00,223.60,5,2019,285000,112.00,0.500894,83 days 15:42:00
3473,2019-05-22 00:00:00,Marta Cury,Vendedor,Filial MG,Guarda Roupa,Casa,489.9,999.00,1,2020-05-08 15:32:00,999.00,5,2019,285000,509.10,0.509610,352 days 15:32:00
3479,2019-10-13 00:00:00,Marta Cury,Vendedor,Filial MG,Guarda Roupa,Casa,489.9,999.00,4,2019-12-05 16:26:00,3996.00,10,2019,285000,2036.40,0.509610,53 days 16:26:00
3485,2020-02-14 00:00:00,Marta Cury,Vendedor,Filial MG,Aspirador de pó,Casa,88.9,189.90,4,2020-04-01 17:40:00,759.60,2,2020,285000,404.00,0.531859,47 days 17:40:00
3486,2019-02-23 00:00:00,Marta Cury,Vendedor,Filial MG,Cama Box,Casa,1189.9,1899.50,3,2019-10-05 17:54:00,5698.50,2,2019,285000,2128.80,0.373572,224 days 17:54:00

In [34]:
df_final.query("valor_final<1000")

,dt_venda,nome_funcionario,cargo,nome_loja,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,mes,ano,meta,lucro,margem_lucro,prazo_entrega
1,2020-06-10 15:34:00,Felipe Marinho,Vendedor,Filial SP,Liquidificador,Cozinha,59.9,142.4,2,2020-06-11 13:59:00,284.8,6,2020,285000,165.0,0.579354,0 days 22:25:00
2,2019-03-21 15:58:00,Felipe Marinho,Vendedor,Filial SP,Fogão,Eletrodomésticos,210.9,404.1,2,2019-03-28 09:44:00,808.2,3,2019,285000,386.4,0.478099,6 days 17:46:00
5,2019-09-28 12:02:00,Felipe Marinho,Vendedor,Filial SP,Colchão,Casa,109.9,249.9,2,2019-09-28 14:06:00,499.8,9,2019,285000,280.0,0.560224,0 days 02:04:00
6,2019-11-01 11:05:00,Felipe Marinho,Vendedor,Filial SP,Fritadeira elétrica,Cozinha,187.9,340.0,2,2019-11-01 13:45:00,680.0,11,2019,285000,304.2,0.447353,0 days 02:40:00
7,2020-11-01 11:48:00,Felipe Marinho,Vendedor,Filial SP,Colchão,Casa,109.9,249.9,2,2020-11-01 12:31:00,499.8,11,2020,285000,280.0,0.560224,0 days 00:43:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3490,2019-06-02 00:00:00,Reginaldo Sodré,Vendedor,Filial MG,Liquidificador,Cozinha,59.9,142.4,3,2019-11-18 16:12:00,427.2,6,2019,285000,247.5,0.579354,169 days 16:12:00
3491,2020-10-12 00:00:00,Mário Henrique,Vendedor,Filial ES,Processador de alimentos,Cozinha,110.0,189.9,1,2019-04-02 12:18:00,189.9,10,2020,285000,79.9,0.420748,-559 days +12:18:00
3494,2019-12-13 00:00:00,José Maria,Vendedor,Loja Matriz,Cafeteira,Cozinha,159.9,284.9,1,2020-09-24 15:31:00,284.9,12,2019,285000,125.0,0.438750,286 days 15:31:00
3495,2019-09-04 00:00:00,Pamela Lima,Vendedor,Filial ES,Colchão,Casa,109.9,249.9,3,2019-04-12 09:04:00,749.7,9,2019,285000,420.0,0.560224,-145 days +09:04:00
3499,2019-07-26 00:00:00,Victor Hugo,Vendedor,Filial ES,Fogão,Eletrodomésticos,210.9,404.1,1,2019-02-25 14:14:00,404.1,7,2019,285000,193.2,0.478099,-151 days +14:14:00

In [35]:
df_final.query("nome_funcionario == 'Jorge Mateus' & valor_final < 1500")

,dt_venda,nome_funcionario,cargo,nome_loja,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,mes,ano,meta,lucro,margem_lucro,prazo_entrega
261,2020-02-25 16:58:00,Jorge Mateus,Vendedor,Loja Matriz,Colchão,Casa,109.9,249.9,2,2020-02-26 14:58:00,499.8,2,2020,285000,280.0,0.560224,0 days 22:00:00
262,2019-09-20 13:24:00,Jorge Mateus,Vendedor,Loja Matriz,Liquidificador,Cozinha,59.9,142.4,2,2019-09-21 11:12:00,284.8,9,2019,285000,165.0,0.579354,0 days 21:48:00
263,2020-05-04 15:25:00,Jorge Mateus,Vendedor,Loja Matriz,Colchão,Casa,109.9,249.9,2,2020-05-04 17:00:00,499.8,5,2020,285000,280.0,0.560224,0 days 01:35:00
266,2020-07-13 11:07:00,Jorge Mateus,Vendedor,Loja Matriz,Microondas,Eletrodomésticos,189.0,364.5,2,2020-07-13 15:08:00,729.0,7,2020,285000,351.0,0.481481,0 days 04:01:00
268,2019-08-29 16:53:00,Jorge Mateus,Vendedor,Loja Matriz,Liquidificador,Cozinha,59.9,142.4,2,2019-08-30 14:14:00,284.8,8,2019,285000,165.0,0.579354,0 days 21:21:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3380,2020-11-21 00:00:00,Jorge Mateus,Vendedor,Loja Matriz,Aspirador de pó,Casa,88.9,189.9,3,2019-12-22 10:28:00,569.7,11,2020,285000,303.0,0.531859,-335 days +10:28:00
3382,2020-07-16 00:00:00,Jorge Mateus,Vendedor,Loja Matriz,Impressora,Eletrônicos,329.9,674.1,2,2020-05-28 13:59:00,1348.2,7,2020,285000,688.4,0.510607,-49 days +13:59:00
3395,2020-05-14 00:00:00,Jorge Mateus,Vendedor,Loja Matriz,Batedeira,Cozinha,49.9,95.9,3,2019-03-03 12:30:00,287.7,5,2020,285000,138.0,0.479666,-438 days +12:30:00
3461,2020-01-05 00:00:00,Jorge Mateus,Vendedor,Loja Matriz,Cafeteira,Cozinha,159.9,284.9,1,2019-12-03 11:46:00,284.9,1,2020,285000,125.0,0.438750,-33 days +11:46:00
3487,2020-09-20 00:00:00,Jorge Mateus,Vendedor,Loja Matriz,Microondas,Eletrodomésticos,189.0,364.5,2,2019-07-25 17:20:00,729.0,9,2020,285000,351.0,0.481481,-423 days +17:20:00

In [36]:
#AGRUPAMENTO - reset_index serve para deixar extruturado o titulo e o sort.values serve para deixa do maior para o menor o true deixa menor e false maior

vendedores_vf = df_final.groupby('nome_funcionario')['valor_final'].sum().sort_values(ascending=False).reset_index()

display(vendedores_vf)

    nome_funcionario  valor_final
0         José Maria    769628.66
1   Maria das Graças    768765.52
2     Felipe Marinho    676213.98
3     Mário Henrique    661754.15
4        Pamela Lima    656664.60
5       Rita Sampaio    647103.53
6        Victor Hugo    639941.37
7       Jorge Mateus    630363.14
8         Marta Cury    621332.54
9    Reginaldo Sodré    612214.89
10     Ricardo Lemos    591359.11
11     Marcos Coelho    553984.01

In [37]:
#agrupar por vendedor e somar tambem

vendedores_vf_qtd = df_final.groupby('nome_funcionario')[['valor_final','lucro']].sum().sort_values(by='lucro',ascending=False).reset_index()

display(vendedores_vf_qtd)

    nome_funcionario  valor_final      lucro
0   Maria das Graças    768765.52  311164.42
1         José Maria    769628.66  310298.26
2     Felipe Marinho    676213.98  283624.88
3        Victor Hugo    639941.37  268997.57
4        Pamela Lima    656664.60  266392.10
5       Rita Sampaio    647103.53  266322.73
6     Mário Henrique    661754.15  265365.75
7         Marta Cury    621332.54  259784.24
8       Jorge Mateus    630363.14  253738.04
9    Reginaldo Sodré    612214.89  253534.39
10     Ricardo Lemos    591359.11  251940.91
11     Marcos Coelho    553984.01  231531.01

In [38]:
#quem mais vendeu por cada produto

vendedores_vf_qtd = df_final.groupby(['nome_funcionario','descricao_produto'])['quantidade'].sum()

display(vendedores_vf_qtd)

nome_funcionario  descricao_produto
Felipe Marinho    Aspirador de pó             40
                  Batedeira                   31
                  Cafeteira                   47
                  Cama Box                    30
                  Colchão                     49
                                              ..
Victor Hugo       Processador de alimentos    46
                  Smartphone                  48
                  Sofá                        27
                  Tablet                      27
                  Televisão                   40
Name: quantidade, Length: 240, dtype: int64

In [39]:
#quem mais vendeu o produto sozinho

vendedores_vf_qtd = df_final.groupby(['nome_funcionario','descricao_produto'])['quantidade'].sum().sort_values(ascending=False).reset_index()

display(vendedores_vf_qtd)

    nome_funcionario         descricao_produto  quantidade
0         José Maria                    Tablet          69
1        Victor Hugo            Liquidificador          68
2       Rita Sampaio       Máquina Lavar Roupa          59
3         José Maria                Impressora          59
4        Pamela Lima       Fritadeira elétrica          58
..               ...                       ...         ...
235       Marta Cury                    Tablet          18
236     Rita Sampaio                 Geladeira          18
237   Felipe Marinho           Ferro de passar          17
238     Jorge Mateus  Processador de alimentos          16
239     Rita Sampaio            Liquidificador          16

[240 rows x 3 columns]

In [40]:
vendas_vf_qtd = df_final.groupby('nome_funcionario').agg({
    'valor_final':['sum','mean'],
    'quantidade':['min','max','mean']
}).reset_index()

display(vendas_vf_qtd)

    nome_funcionario valor_final              quantidade
                             sum         mean        min max      mean
0     Felipe Marinho   676213.98  2284.506689          1   4  2.537162
1       Jorge Mateus   630363.14  2151.410034          1   4  2.389078
2         José Maria   769628.66  2390.151118          1   4  2.450311
3      Marcos Coelho   553984.01  1916.899689          1   4  2.259516
4   Maria das Graças   768765.52  2365.432369          1   4  2.501538
5         Marta Cury   621332.54  2219.044786          1   4  2.510714
6     Mário Henrique   661754.15  2535.456513          1   4  2.567050
7        Pamela Lima   656664.60  2477.979623          1   4  2.569811
8    Reginaldo Sodré   612214.89  2013.864770          1   4  2.388158
9      Ricardo Lemos   591359.11  2067.689196          1   4  2.430070
10      Rita Sampaio   647103.53  2270.538702          1   4  2.477193
11       Victor Hugo   639941.37  2176.671327          1   4  2.489796

In [41]:
#GRAFICOS

import plotly.express as px

In [48]:
receitas_lojas = df_final.groupby('nome_loja')['valor_final'].sum().sort_values(ascending=False).reset_index()
#display(receitas_lojas) mostra os graficos isso

fig = px.bar(receitas_lojas, x='nome_loja', y='valor_final',title='RECEITAS POR LOJAS',color='valor_final',color_continuous_scale=px.colors.diverging.RdBu_r)

fig.update_traces(textposition='outside',texttemplate='%{text:.10s}')

fig.show()

In [49]:
qtd_prod = df_final.groupby('descricao_produto')['quantidade'].sum().sort_values(inplace=False).reset_index()
display(qtd_prod)

           descricao_produto  quantidade
0                       Sofá         349
1                   Notebook         367
2                  Cafeteira         384
3                  Batedeira         385
4                  Geladeira         388
5                   Cama Box         415
6   Processador de alimentos         418
7               Guarda Roupa         422
8                  Televisão         424
9                 Smartphone         427
10                   Colchão         430
11                Impressora         444
12                    Tablet         444
13       Máquina Lavar Roupa         453
14            Liquidificador         454
15                     Fogão         463
16       Fritadeira elétrica         464
17           Ferro de passar         481
18                Microondas         486
19           Aspirador de pó         521

In [51]:
fig = px.bar(qtd_prod, x='descricao_produto', y='quantidade',color='quantidade', title='DESCRICÃO VS QUANTIDADE',text=qtd_prod['quantidade'],color_continuous_scale=px.colors.sequential.Inferno)
fig.update_traces(textposition='outside')
fig.show()

In [62]:
fat_lojas = df_final.groupby('nome_loja').agg({'valor_final':'sum', 'lucro':'sum'}).sort_values(by='valor_final', ascending=False).reset_index()

fig = px.bar(fat_lojas, x='nome_loja', y=['valor_final','lucro'], barmode='group', text_auto=True)

fig.update_traces(textposition='outside')

fig.show()

In [75]:
df_final['ano - mes'] = df_final['dt_venda'].dt.to_period('M')
df_fat_mes = df_final.groupby('ano - mes')['valor_final'].sum().reset_index()
df_fat_mes['ano - mes'] = df_fat_mes['ano - mes'].dt.to_timestamp()

fig = px.line(df_fat_mes, x='ano - mes', y='valor_final', line_shape='spline', markers='1')

fig.show()

In [74]:
fig = px.pie(categorias, names='categoria', values='count',height=500, width=500, title='CATEGORIAS DOS PRODUTOS')

fig.update_traces(hole=0.2,pull=[0.1])

fig.show()

In [76]:
lucro_vf = df_final.groupby('descricao_produto').agg({
    'valor_final':'sum',
    'lucro':'sum',
    'quantidade':'sum'
}).reset_index()

fig = px.scatter(lucro_vf, x='lucro', y='valor_final', color='descricao_produto', size='quantidade', size_max=25)

fig.show()

In [77]:
vendedores_geral = df_final.groupby(['nome_loja','nome_funcionario','descricao_produto'])['lucro'].sum().reset_index()
#display(vendedores_geral)
fig = px.treemap(vendedores_geral, path=[px.Constant('Geral'),'nome_loja','nome_funcionario','descricao_produto'], values='lucro')

fig.show()

In [78]:
fig = px.sunburst(vendedores_geral, path=[px.Constant('Geral'),'nome_loja','nome_funcionario','descricao_produto'], values='lucro')

fig.show()