<a href="https://colab.research.google.com/github/maryreginaf15/AnaliseDeDaDosComIA/blob/main/AnaliseDescritiva.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
import pandas as pd

In [ ]:
#importacao de dados


#df_vendas1 = pd.read_csv("/content/base_dados_vendas_tratada.csv")
#df_vendas2 = pd.read_csv("/content/dados_complementares.csv")
#df_metas = pd.read_excel("/content/Python_JOIN_Metas.xlsx")
df_vendas1 = pd.read_csv("/content/base_dados_vendas_tratada.csv",parse_dates = ['dt_venda', 'dt_entrega'])
df_vendas2 = pd.read_csv("/content/dados_complementares.csv",parse_dates = ['dt_venda', 'dt_entrega'])
df_metas = pd.read_excel("/content/Python_JOIN_Metas.xlsx")

In [ ]:

df_vendas1.head()

,dt_venda,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final
0,2020-08-25 10:04:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,3,2020-08-31 16:39:00,1212.3
1,2020-06-10 15:34:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10011,Liquidificador,Cozinha,59.9,142.4,2,2020-06-11 13:59:00,284.8
2,2019-03-21 15:58:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,2,2019-03-28 09:44:00,808.2
3,2019-09-16 14:46:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,2,2019-09-20 09:22:00,3418.2
4,2019-11-25 16:28:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10005,Notebook,Eletrônicos,2299.9,3199.0,2,2019-11-26 13:42:00,6398.0

In [ ]:
df_vendas2.head()

,dt_venda,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final
0,2020-03-20,123456111,José Maria,Vendedor,CL001,Loja Matriz,10006,Aspirador de pó,Casa,88.9,189.9,4,2019-03-29 16:37:00,759.6
1,2019-12-22,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10014,Geladeira,Eletrodomésticos,699.9,1346.9,3,2020-07-23 10:54:00,4040.7
2,2019-12-18,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,3,2020-09-04 10:50:00,287.7
3,2019-09-02,123456444,Ricardo Lemos,Vendedor,CL002,Filial MG,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,1,2019-03-28 09:36:00,1709.1
4,2019-01-15,123456222,Maria das Graças,Vendedor,CL001,Loja Matriz,10009,Ferro de passar,Casa,27.9,55.9,3,2020-02-04 15:50:00,167.7

In [ ]:
df_metas.head()

    ano  mes    meta
0  2019    1  285000
1  2019    2  285000
2  2019    3  285000
3  2019    4  285000
4  2019    5  285000

In [ ]:
df_vendas1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   dt_venda               3000 non-null   datetime64[ns]
 1   matricula_funcionario  3000 non-null   int64
 2   nome_funcionario       3000 non-null   object
 3   cargo                  3000 non-null   object
 4   codigo_loja            3000 non-null   object
 5   nome_loja              3000 non-null   object
 6   codigo_produto         3000 non-null   int64
 7   descricao_produto      3000 non-null   object
 8   categoria              3000 non-null   object
 9   preco_custo            3000 non-null   float64
 10  valor_unitario         3000 non-null   float64
 11  quantidade             3000 non-null   int64
 12  dt_entrega             3000 non-null   datetime64[ns]
 13  valor_final            3000 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(6)
memory usage: 328.3+ KB

In [ ]:
df_vendas1[['preco_custo','valor_unitario','quantidade','valor_final']].describe().round(2)

       preco_custo  valor_unitario  quantidade  valor_final
count      3000.00         3000.00     3000.00      3000.00
mean        545.51          926.94        2.45      2234.95
std         563.13          841.84        1.11      2449.47
min          27.90           55.90        1.00        55.90
25%         109.90          189.90        1.00       427.20
50%         210.90          404.10        2.00      1346.90
75%         799.00         1424.91        3.00      3353.80
max        2299.90         3199.00        4.00     12796.00

In [ ]:
df_vendas2[['preco_custo','valor_unitario','quantidade','valor_final']].describe().round(2)

       preco_custo  valor_unitario  quantidade  valor_final
count       500.00          500.00      500.00       500.00
mean        550.18          925.93        2.52      2248.96
std         581.42          861.32        1.12      2427.84
min          27.90           55.90        1.00        55.90
25%         110.00          249.90        1.00       499.80
50%         210.90          404.10        3.00      1139.60
75%         899.90         1676.90        3.00      3418.20
max        2299.90         3199.00        4.00     12796.00

In [ ]:
df_metas.describe()

               ano        mes      meta
count    24.000000  24.000000      24.0
mean   2019.500000   6.500000  285000.0
std       0.510754   3.526299       0.0
min    2019.000000   1.000000  285000.0
25%    2019.000000   3.750000  285000.0
50%    2019.500000   6.500000  285000.0
75%    2020.000000   9.250000  285000.0
max    2020.000000  12.000000  285000.0

In [ ]:
#juncao do dados
#concatenar

df_vendas = pd.concat([df_vendas1,df_vendas2], axis=0, join='outer' )#
df_vendas.head()

,dt_venda,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final
0,2020-08-25 10:04:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,3,2020-08-31 16:39:00,1212.3
1,2020-06-10 15:34:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10011,Liquidificador,Cozinha,59.9,142.4,2,2020-06-11 13:59:00,284.8
2,2019-03-21 15:58:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,2,2019-03-28 09:44:00,808.2
3,2019-09-16 14:46:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,2,2019-09-20 09:22:00,3418.2
4,2019-11-25 16:28:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10005,Notebook,Eletrônicos,2299.9,3199.0,2,2019-11-26 13:42:00,6398.0

In [ ]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   dt_venda               3500 non-null   datetime64[ns]
 1   matricula_funcionario  3500 non-null   int64
 2   nome_funcionario       3500 non-null   object
 3   cargo                  3500 non-null   object
 4   codigo_loja            3500 non-null   object
 5   nome_loja              3500 non-null   object
 6   codigo_produto         3500 non-null   int64
 7   descricao_produto      3500 non-null   object
 8   categoria              3500 non-null   object
 9   preco_custo            3500 non-null   float64
 10  valor_unitario         3500 non-null   float64
 11  quantidade             3500 non-null   int64
 12  dt_entrega             3500 non-null   datetime64[ns]
 13  valor_final            3500 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(6)
memory usage: 410.2+ KB

In [ ]:
display(df_vendas)

,dt_venda,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final
0,2020-08-25 10:04:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.10,3,2020-08-31 16:39:00,1212.30
1,2020-06-10 15:34:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10011,Liquidificador,Cozinha,59.9,142.40,2,2020-06-11 13:59:00,284.80
2,2019-03-21 15:58:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.10,2,2019-03-28 09:44:00,808.20
3,2019-09-16 14:46:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.10,2,2019-09-20 09:22:00,3418.20
4,2019-11-25 16:28:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10005,Notebook,Eletrônicos,2299.9,3199.00,2,2019-11-26 13:42:00,6398.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,2019-09-04 00:00:00,123457111,Pamela Lima,Vendedor,CL004,Filial ES,10018,Colchão,Casa,109.9,249.90,3,2019-04-12 09:04:00,749.70
496,2020-05-02 00:00:00,123456111,José Maria,Vendedor,CL001,Loja Matriz,10017,Cama Box,Casa,1189.9,1899.50,3,2020-03-11 10:27:00,5698.50
497,2020-06-14 00:00:00,123456333,Jorge Mateus,Vendedor,CL001,Loja Matriz,10003,Televisão,Eletrodomésticos,1400.9,2279.99,1,2019-04-07 15:45:00,2279.99
498,2020-11-04 00:00:00,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.10,3,2019-11-05 15:44:00,5127.30
499,2019-07-26 00:00:00,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10013,Fogão,Eletrodomésticos,210.9,404.10,1,2019-02-25 14:14:00,404.10

In [ ]:
df_vendas.duplicated().sum()

np.int64(0)

In [56]:
#mesclagem

df_vendas['mes'] = df_vendas['dt_venda'].dt.month
df_vendas['ano'] = df_vendas['dt_venda'].dt.year

In [57]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3500 entries, 0 to 499
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   dt_venda               3500 non-null   datetime64[ns]
 1   matricula_funcionario  3500 non-null   int64
 2   nome_funcionario       3500 non-null   object
 3   cargo                  3500 non-null   object
 4   codigo_loja            3500 non-null   object
 5   nome_loja              3500 non-null   object
 6   codigo_produto         3500 non-null   int64
 7   descricao_produto      3500 non-null   object
 8   categoria              3500 non-null   object
 9   preco_custo            3500 non-null   float64
 10  valor_unitario         3500 non-null   float64
 11  quantidade             3500 non-null   int64
 12  dt_entrega             3500 non-null   datetime64[ns]
 13  valor_final            3500 non-null   float64
 14  mes                    3500 non-null   int32
 15  ano                    3500 non-null   int32
dtypes: datetime64[ns](2), float64(3), int32(2), int64(3), object(6)
memory usage: 437.5+ KB

In [58]:
df_final = df_vendas.merge(df_metas, on=['ano', 'mes'],how='inner')

In [60]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   dt_venda               3500 non-null   datetime64[ns]
 1   matricula_funcionario  3500 non-null   int64
 2   nome_funcionario       3500 non-null   object
 3   cargo                  3500 non-null   object
 4   codigo_loja            3500 non-null   object
 5   nome_loja              3500 non-null   object
 6   codigo_produto         3500 non-null   int64
 7   descricao_produto      3500 non-null   object
 8   categoria              3500 non-null   object
 9   preco_custo            3500 non-null   float64
 10  valor_unitario         3500 non-null   float64
 11  quantidade             3500 non-null   int64
 12  dt_entrega             3500 non-null   datetime64[ns]
 13  valor_final            3500 non-null   float64
 14  mes                    3500 non-null   int32
 15  ano                    3500 non-null   int32
 16  meta                   3500 non-null   int64
dtypes: datetime64[ns](2), float64(3), int32(2), int64(4), object(6)
memory usage: 437.6+ KB

In [61]:
df_final['lucro'] = (df_final['valor_unitario'] - df_final['preco_custo']) * df_final['quantidade']
df_final['margem_lucro'] = (df_final['valor_unitario'] - df_final['preco_custo']) / df_final['valor_unitario']
df_final['prazo_entrega'] = df_final['dt_entrega'] - df_final['dt_venda']
df_final['valor_final'] = df_final['valor_unitario'] * df_final['quantidade']

In [66]:
df_final.drop(columns=['matricula_funcionario','codigo_produto','codigo_loja'],inplace=True)

In [65]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   dt_venda               3500 non-null   datetime64[ns]
 1   matricula_funcionario  3500 non-null   int64
 2   nome_funcionario       3500 non-null   object
 3   cargo                  3500 non-null   object
 4   codigo_loja            3500 non-null   object
 5   nome_loja              3500 non-null   object
 6   codigo_produto         3500 non-null   int64
 7   descricao_produto      3500 non-null   object
 8   categoria              3500 non-null   object
 9   preco_custo            3500 non-null   float64
 10  valor_unitario         3500 non-null   float64
 11  quantidade             3500 non-null   int64
 12  dt_entrega             3500 non-null   datetime64[ns]
 13  valor_final            3500 non-null   float64
 14  mes                    3500 non-null   int32
 15  ano                    3500 non-null   int32
 16  meta                   3500 non-null   int64
 17  lucro                  3500 non-null   float64
 18  margem_lucro           3500 non-null   float64
 19  prazo_entrega          3500 non-null   timedelta64[ns]
dtypes: datetime64[ns](2), float64(5), int32(2), int64(4), object(6), timedelta64[ns](1)
memory usage: 519.7+ KB

In [67]:
#salvando a base

df_final.to_csv("/content/base_dados_tratada.csv")

In [ ]:
#analise descritiva

#fiLTROS LOGICO DE DADOS

# > MAIOR QUE
# < MENOR QIE
# >= MAIOR OU IGUAL QUE
#<= MENOR OU IGUAL QUE
# == IGUAL A
# != DIFERENTE DE
# & (E)
# | (OU )
# ~ (NÃO )
#
#
#

In [68]:
df_final.nome_loja.unique()

array(['Filial SP', 'Loja Matriz', 'Filial MG', 'Filial ES'], dtype=object)

In [69]:
df_final.nome_funcionario.unique()

array(['Felipe Marinho', 'Jorge Mateus', 'José Maria', 'Marcos Coelho',
       'Maria das Graças', 'Marta Cury', 'Mário Henrique', 'Pamela Lima',
       'Reginaldo Sodré', 'Ricardo Lemos', 'Rita Sampaio', 'Victor Hugo'],
      dtype=object)

In [70]:
df_final.descricao_produto.unique()

array(['Fogão', 'Liquidificador', 'Máquina Lavar Roupa', 'Notebook',
       'Colchão', 'Fritadeira elétrica', 'Televisão', 'Sofá',
       'Processador de alimentos', 'Ferro de passar', 'Guarda Roupa',
       'Tablet', 'Aspirador de pó', 'Geladeira', 'Smartphone',
       'Microondas', 'Cafeteira', 'Batedeira', 'Impressora', 'Cama Box'],
      dtype=object)