<a href="https://colab.research.google.com/github/maryreginaf15/AnaliseDeDaDosComIA/blob/main/etldados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#manipulacao de dados

import pandas as pd

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
#importando a base

df_vendas = pd.read_csv("/content/drive/MyDrive/DADOS/base_vendas.csv")
display(df_vendas)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,"88,9","189,9",3,NaN,04/11/2019 15:40,05/11/2019 10:40
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,"59,9","142,4",3,NaN,24/06/2019 09:04,24/06/2019 10:50
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,"49,9","95,9",3,NaN,08/08/2020 14:46,09/08/2020 14:07
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,"187,9",340,3,NaN,19/12/2019 09:21,19/12/2019 10:51
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",3,"0,09",18/03/2019 15:40,23/03/2019 17:52

In [7]:
df_vendas.head(15)
df_vendas.tail(15)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
2985,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",3,"0,09",10/05/2019 17:16,17/05/2019 12:42
2986,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10012,Processador de alimentos,Cozinha,110,"189,9",3,NaN,24/01/2020 11:16,24/01/2020 16:20
2987,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10002,Tablet,Eletrônicos,799,"1424,91",3,NaN,06/03/2019 11:01,06/03/2019 17:29
2988,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,"59,9","142,4",3,NaN,05/05/2020 15:56,06/05/2020 15:20
2989,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10002,Tablet,Eletrônicos,799,"1424,91",3,NaN,26/05/2020 14:53,27/05/2020 11:01
2990,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",3,NaN,04/12/2020 13:24,10/12/2020 11:05
2991,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10016,Guarda Roupa,Casa,"489,9",999,3,NaN,13/06/2020 16:58,15/06/2020 17:41
2992,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,"187,9",340,3,NaN,02/07/2019 16:56,03/07/2019 09:27
2993,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10001,Smartphone,Eletrônicos,"899,9","1676,9",3,NaN,18/12/2019 17:59,19/12/2019 16:33
2994,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10001,Smartphone,Eletrônicos,"899,9","1676,9",3,NaN,26/01/2019 16:06,26/01/2019 16:16
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,"88,9","189,9",3,NaN,04/11/2019 15:40,05/11/2019 10:40
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,"59,9","142,4",3,NaN,24/06/2019 09:04,24/06/2019 10:50
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,"49,9","95,9",3,NaN,08/08/2020 14:46,09/08/2020 14:07
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,"187,9",340,3,NaN,19/12/2019 09:21,19/12/2019 10:51
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",3,"0,09",18/03/2019 15:40,23/03/2019 17:52

In [8]:
df_vendas.shape

(3000, 14)

In [9]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   int64
 1   Nome Funcionario       3000 non-null   object
 2   Cargo                  3000 non-null   object
 3   codigo_loja            3000 non-null   object
 4   nome_loja              3000 non-null   object
 5   codigo_produto         3000 non-null   int64
 6   descricao_produto      3000 non-null   object
 7   Categoria              3000 non-null   object
 8   preco_custo            3000 non-null   object
 9   valor_unitario         3000 non-null   object
 10  quantidade             3000 non-null   int64
 11  comissao               159 non-null    object
 12  dt_venda               3000 non-null   object
 13  dt_entrega             3000 non-null   object
dtypes: int64(3), object(11)
memory usage: 328.3+ KB

In [10]:
#mostrar as colunas

df_vendas.columns

Index(['matricula_funcionario', 'Nome Funcionario', 'Cargo', 'codigo_loja',
       'nome_loja', 'codigo_produto', 'descricao_produto', 'Categoria',
       'preco_custo', 'valor_unitario', 'quantidade', 'comissao', 'dt_venda',
       'dt_entrega'],
      dtype='object')

In [11]:
#padronizar os nomes das colunas
nome_colunas =  df_vendas.columns

In [12]:
# list comprehension
# dist comprehension

[i for i in range(20)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [13]:
#padronizar os nomes das colunas (snake_case)

nome_colunas = df_vendas.columns

#print(nome_colunas)

df_vendas.columns = [i.strip().lower().replace(" ", "_") for i in nome_colunas]
df_vendas.columns

df_vendas

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,"88,9","189,9",3,NaN,04/11/2019 15:40,05/11/2019 10:40
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,"59,9","142,4",3,NaN,24/06/2019 09:04,24/06/2019 10:50
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,"49,9","95,9",3,NaN,08/08/2020 14:46,09/08/2020 14:07
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,"187,9",340,3,NaN,19/12/2019 09:21,19/12/2019 10:51
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",3,"0,09",18/03/2019 15:40,23/03/2019 17:52

In [14]:
#desricao do arquivo round(2) =  serve para aumentar duas casas decimais
df_vendas.describe().round(2)

       matricula_funcionario  codigo_produto  quantidade
count           3.000000e+03         3000.00     3000.00
mean            1.234567e+08        10010.47        2.45
std             3.490000e+02            5.77        1.11
min             1.234561e+08        10001.00        1.00
25%             1.234563e+08        10006.00        1.00
50%             1.234567e+08        10011.00        2.00
75%             1.234570e+08        10015.00        3.00
max             1.234571e+08        10020.00        4.00

In [15]:
df_vendas.describe(include="all")

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
count,3.000000e+03,3000,3000,3000,3000,3000.000000,3000,3000,3000,3000,3000.000000,159,3000,3000
unique,NaN,12,1,4,4,NaN,20,4,20,19,NaN,4,2994,2989
top,NaN,José Maria,Vendedor,CL001,Loja Matriz,NaN,Aspirador de pó,Casa,"88,9","189,9",NaN,"0,05",09/07/2019 16:05,09/12/2019 10:12
freq,NaN,280,3000,793,793,NaN,173,907,173,316,NaN,49,2,2
mean,1.234567e+08,NaN,NaN,NaN,NaN,10010.468667,NaN,NaN,NaN,NaN,2.453333,NaN,NaN,NaN
std,3.489977e+02,NaN,NaN,NaN,NaN,5.772590,NaN,NaN,NaN,NaN,1.107955,NaN,NaN,NaN
min,1.234561e+08,NaN,NaN,NaN,NaN,10001.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN
25%,1.234563e+08,NaN,NaN,NaN,NaN,10006.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN
50%,1.234567e+08,NaN,NaN,NaN,NaN,10011.000000,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN
75%,1.234570e+08,NaN,NaN,NaN,NaN,10015.000000,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN
max,1.234571e+08,NaN,NaN,NaN,NaN,10020.000000,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN

In [16]:
df_vendas.describe(include="object")

,nome_funcionario,cargo,codigo_loja,nome_loja,descricao_produto,categoria,preco_custo,valor_unitario,comissao,dt_venda,dt_entrega
count,3000,3000,3000,3000,3000,3000,3000,3000,159,3000,3000
unique,12,1,4,4,20,4,20,19,4,2994,2989
top,José Maria,Vendedor,CL001,Loja Matriz,Aspirador de pó,Casa,"88,9","189,9","0,05",09/07/2019 16:05,09/12/2019 10:12
freq,280,3000,793,793,173,907,173,316,49,2,2

In [17]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   int64
 1   nome_funcionario       3000 non-null   object
 2   cargo                  3000 non-null   object
 3   codigo_loja            3000 non-null   object
 4   nome_loja              3000 non-null   object
 5   codigo_produto         3000 non-null   int64
 6   descricao_produto      3000 non-null   object
 7   categoria              3000 non-null   object
 8   preco_custo            3000 non-null   object
 9   valor_unitario         3000 non-null   object
 10  quantidade             3000 non-null   int64
 11  comissao               159 non-null    object
 12  dt_venda               3000 non-null   object
 13  dt_entrega             3000 non-null   object
dtypes: int64(3), object(11)
memory usage: 328.3+ KB

In [18]:
#tratamento de  horas e datas

df_vendas['dt_venda'] = pd.to_datetime(df_vendas['dt_venda'], format='%d/%m/%Y %H:%M')
df_vendas['dt_entrega'] = pd.to_datetime(df_vendas['dt_entrega'], format='%d/%m/%Y %H:%M')

In [19]:
df_vendas
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   int64
 1   nome_funcionario       3000 non-null   object
 2   cargo                  3000 non-null   object
 3   codigo_loja            3000 non-null   object
 4   nome_loja              3000 non-null   object
 5   codigo_produto         3000 non-null   int64
 6   descricao_produto      3000 non-null   object
 7   categoria              3000 non-null   object
 8   preco_custo            3000 non-null   object
 9   valor_unitario         3000 non-null   object
 10  quantidade             3000 non-null   int64
 11  comissao               159 non-null    object
 12  dt_venda               3000 non-null   datetime64[ns]
 13  dt_entrega             3000 non-null   datetime64[ns]
dtypes: datetime64[ns](2), int64(3), object(9)
memory usage: 328.3+ KB

In [20]:
df_vendas['preco_custo']= df_vendas['preco_custo'].str.replace(',','.')
df_vendas['valor_unitario']= df_vendas['valor_unitario'].str.replace(',','.')
df_vendas['comissao']= df_vendas['comissao'].str.replace(',','.')

df_vendas

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,210.9,404.1,1,NaN,2020-09-28 16:19:00,2020-10-05 16:31:00
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,109.9,249.9,1,NaN,2020-03-07 12:47:00,2020-03-08 12:47:00
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,699.9,1346.9,1,NaN,2019-04-21 10:48:00,2019-04-23 15:55:00
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,899.9,1676.9,1,NaN,2020-05-07 17:59:00,2020-05-08 14:31:00
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,1709.1,1,0.05,2019-08-14 16:56:00,2019-08-19 15:52:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,88.9,189.9,3,NaN,2019-11-04 15:40:00,2019-11-05 10:40:00
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,59.9,142.4,3,NaN,2019-06-24 09:04:00,2019-06-24 10:50:00
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,49.9,95.9,3,NaN,2020-08-08 14:46:00,2020-08-09 14:07:00
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,187.9,340,3,NaN,2019-12-19 09:21:00,2019-12-19 10:51:00
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,1709.1,3,0.09,2019-03-18 15:40:00,2019-03-23 17:52:00

In [21]:
df_vendas['preco_custo']= df_vendas['preco_custo'].astype(float)
df_vendas['valor_unitario']= df_vendas['valor_unitario'].astype(float)
df_vendas['comissao']= df_vendas['comissao'].astype(float)
df_vendas

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,210.9,404.1,1,NaN,2020-09-28 16:19:00,2020-10-05 16:31:00
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,109.9,249.9,1,NaN,2020-03-07 12:47:00,2020-03-08 12:47:00
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,699.9,1346.9,1,NaN,2019-04-21 10:48:00,2019-04-23 15:55:00
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,899.9,1676.9,1,NaN,2020-05-07 17:59:00,2020-05-08 14:31:00
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,1,0.05,2019-08-14 16:56:00,2019-08-19 15:52:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,88.9,189.9,3,NaN,2019-11-04 15:40:00,2019-11-05 10:40:00
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,59.9,142.4,3,NaN,2019-06-24 09:04:00,2019-06-24 10:50:00
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,49.9,95.9,3,NaN,2020-08-08 14:46:00,2020-08-09 14:07:00
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,187.9,340.0,3,NaN,2019-12-19 09:21:00,2019-12-19 10:51:00
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,3,0.09,2019-03-18 15:40:00,2019-03-23 17:52:00

In [22]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   int64
 1   nome_funcionario       3000 non-null   object
 2   cargo                  3000 non-null   object
 3   codigo_loja            3000 non-null   object
 4   nome_loja              3000 non-null   object
 5   codigo_produto         3000 non-null   int64
 6   descricao_produto      3000 non-null   object
 7   categoria              3000 non-null   object
 8   preco_custo            3000 non-null   float64
 9   valor_unitario         3000 non-null   float64
 10  quantidade             3000 non-null   int64
 11  comissao               159 non-null    float64
 12  dt_venda               3000 non-null   datetime64[ns]
 13  dt_entrega             3000 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(3), int64(3), object(6)
memory usage: 328.3+ KB

In [23]:
df_vendas.describe()

,matricula_funcionario,codigo_produto,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
count,3.000000e+03,3000.000000,3000.000000,3000.000000,3000.000000,159.000000,3000,3000
mean,1.234567e+08,10010.468667,545.512300,926.941353,2.453333,0.074465,2019-12-26 16:18:31.819999744,2019-12-28 13:30:03.600000
min,1.234561e+08,10001.000000,27.900000,55.900000,1.000000,0.050000,2019-01-01 09:08:00,2019-01-01 14:07:00
25%,1.234563e+08,10006.000000,109.900000,189.900000,1.000000,0.050000,2019-06-22 06:13:00,2019-06-25 05:15:15
50%,1.234567e+08,10011.000000,210.900000,404.100000,2.000000,0.070000,2019-12-18 17:39:30,2019-12-21 10:46:00
75%,1.234570e+08,10015.000000,799.000000,1424.910000,3.000000,0.090000,2020-06-28 11:34:00,2020-06-30 15:31:45
max,1.234571e+08,10020.000000,2299.900000,3199.000000,4.000000,0.100000,2020-12-31 15:07:00,2020-12-31 17:37:00
std,3.489977e+02,5.772590,563.133526,841.839695,1.107955,0.019508,NaN,NaN

In [24]:
df_vendas

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,210.9,404.1,1,NaN,2020-09-28 16:19:00,2020-10-05 16:31:00
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,109.9,249.9,1,NaN,2020-03-07 12:47:00,2020-03-08 12:47:00
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,699.9,1346.9,1,NaN,2019-04-21 10:48:00,2019-04-23 15:55:00
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,899.9,1676.9,1,NaN,2020-05-07 17:59:00,2020-05-08 14:31:00
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,1,0.05,2019-08-14 16:56:00,2019-08-19 15:52:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,88.9,189.9,3,NaN,2019-11-04 15:40:00,2019-11-05 10:40:00
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,59.9,142.4,3,NaN,2019-06-24 09:04:00,2019-06-24 10:50:00
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,49.9,95.9,3,NaN,2020-08-08 14:46:00,2020-08-09 14:07:00
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,187.9,340.0,3,NaN,2019-12-19 09:21:00,2019-12-19 10:51:00
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,3,0.09,2019-03-18 15:40:00,2019-03-23 17:52:00

In [25]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   int64
 1   nome_funcionario       3000 non-null   object
 2   cargo                  3000 non-null   object
 3   codigo_loja            3000 non-null   object
 4   nome_loja              3000 non-null   object
 5   codigo_produto         3000 non-null   int64
 6   descricao_produto      3000 non-null   object
 7   categoria              3000 non-null   object
 8   preco_custo            3000 non-null   float64
 9   valor_unitario         3000 non-null   float64
 10  quantidade             3000 non-null   int64
 11  comissao               159 non-null    float64
 12  dt_venda               3000 non-null   datetime64[ns]
 13  dt_entrega             3000 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(3), int64(3), object(6)
memory usage: 328.3+ KB

In [26]:
#tratamento dos valores nulos
#preencher os valores nulos os Nan (nuloscom um valor pre-definido de forma manual )

#df_vendas['comissao'].fillna(0, inplace=True)
df_vendas.isna().sum()

matricula_funcionario       0
nome_funcionario            0
cargo                       0
codigo_loja                 0
nome_loja                   0
codigo_produto              0
descricao_produto           0
categoria                   0
preco_custo                 0
valor_unitario              0
quantidade                  0
comissao                 2841
dt_venda                    0
dt_entrega                  0
dtype: int64

In [27]:
df_vendas['comissao']

0        NaN
1        NaN
2        NaN
3        NaN
4       0.05
        ...
2995     NaN
2996     NaN
2997     NaN
2998     NaN
2999    0.09
Name: comissao, Length: 3000, dtype: float64

In [28]:
#preencher os valores nulos com a media

valor_medio = df_vendas['comissao'].mean()
print(valor_medio)

df_vendas['comissao'].fillna(valor_medio, inplace=True)

0.07446540880503144

In [29]:
valor_moda = df_vendas['comissao'].mode()
print(valor_moda)

df_vendas['comissao'].fillna(valor_moda, inplace=True)

0    0.074465
Name: comissao, dtype: float64

In [30]:
#preenchendo so valores de baixo para cimar


df_vendas['comissao'].ffill(inplace=True)
#df_vendas['comissao'].fillna(method='bfill', inplace=True)

In [31]:
#preenchendo os valores com bfiff
df_vendas['comissao'].bfill(inplace=True)

In [32]:
#remover matriculas de funcionarios e codigo do produto

df_vendas.drop(columns=['matricula_funcionario', 'codigo_produto'],inplace=True)

In [33]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   nome_funcionario   3000 non-null   object
 1   cargo              3000 non-null   object
 2   codigo_loja        3000 non-null   object
 3   nome_loja          3000 non-null   object
 4   descricao_produto  3000 non-null   object
 5   categoria          3000 non-null   object
 6   preco_custo        3000 non-null   float64
 7   valor_unitario     3000 non-null   float64
 8   quantidade         3000 non-null   int64
 9   comissao           3000 non-null   float64
 10  dt_venda           3000 non-null   datetime64[ns]
 11  dt_entrega         3000 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(3), int64(1), object(6)
memory usage: 281.4+ KB

In [34]:
#engenharia de dados

df_vendas['valor_final'] = df_vendas['quantidade' ]* df_vendas['valor_unitario']
df_vendas['valor_comissao'] = df_vendas ['valor_final' ]* df_vendas['comissao']
df_vendas['lucro_bruto'] = (df_vendas ['valor_final' ]* df_vendas['preco_custo']) * df_vendas['quantidade']
df_vendas['lucro_real'] = df_vendas ['lucro_bruto' ] -  df_vendas['valor_comissao']
df_vendas['margem_lucro'] = (df_vendas ['valor_unitario' ] -  df_vendas['preco_custo'] ) / df_vendas['preco_custo']/ df_vendas['valor_unitario'] * 100
df_vendas['markup'] =  (df_vendas['valor_unitario'] - df_vendas['preco_custo']) / df_vendas['preco_custo'] * 100