<a href="https://colab.research.google.com/github/maryreginaf15/AnaliseDeDaDosComIA/blob/main/extracaoETL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#IMPORTANDO BILIOTECAS PANDAS

import pandas as pd

In [6]:
#dataframe = df
#importando um arq csv separado por virgula

df = pd.read_csv("/content/drive/MyDrive/DADOS/base_vendas.csv")
#print(df)
display(df)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,"88,9","189,9",3,NaN,04/11/2019 15:40,05/11/2019 10:40
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,"59,9","142,4",3,NaN,24/06/2019 09:04,24/06/2019 10:50
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,"49,9","95,9",3,NaN,08/08/2020 14:46,09/08/2020 14:07
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,"187,9",340,3,NaN,19/12/2019 09:21,19/12/2019 10:51
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",3,"0,09",18/03/2019 15:40,23/03/2019 17:52

In [7]:
#display mostras as 5 primeiras e 5 ultimas linhas do df / mostra todas se o arquivo e pequeno

display(df)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,"88,9","189,9",3,NaN,04/11/2019 15:40,05/11/2019 10:40
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,"59,9","142,4",3,NaN,24/06/2019 09:04,24/06/2019 10:50
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,"49,9","95,9",3,NaN,08/08/2020 14:46,09/08/2020 14:07
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,"187,9",340,3,NaN,19/12/2019 09:21,19/12/2019 10:51
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",3,"0,09",18/03/2019 15:40,23/03/2019 17:52

In [8]:
# na primeira vez que abre ele entende que o arq esta separado por virgula
# importando um arq cvs separado por ponto  virgula
# para escolher o separador podemos usar: delimiter "separador" "ou  podemos usar o sep = "separador"


df = pd.read_csv("/content/drive/MyDrive/DADOS/base_vendas_ponto_virgula.csv",sep = ";")

display(df)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,123456111,José Maria,Vendedor,CL001,Loja Matriz,10017,Cama Box,Casa,"1189,9","1899,5",3,NaN,05/03/2020 12:58,11/03/2020 10:27
96,123456111,José Maria,Vendedor,CL001,Loja Matriz,10005,Notebook,Eletrônicos,"2299,9",3199,3,NaN,07/08/2020 13:11,07/08/2020 14:53
97,123456111,José Maria,Vendedor,CL001,Loja Matriz,10020,Impressora,Eletrônicos,"329,9","674,1",3,NaN,29/09/2019 09:05,29/09/2019 12:15
98,123456111,José Maria,Vendedor,CL001,Loja Matriz,10012,Processador de alimentos,Cozinha,110,"189,9",3,NaN,30/09/2019 16:49,01/10/2019 14:55
99,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",3,NaN,08/11/2020 14:32,09/11/2020 09:48

In [9]:
#importando um arq tsv(csv) separado por tabulacao

df = pd.read_csv("/content/drive/MyDrive/DADOS/base_vendas_tab.tsv",sep = "\t")

display(df)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,123456111,José Maria,Vendedor,CL001,Loja Matriz,10017,Cama Box,Casa,"1189,9","1899,5",3,NaN,05/03/2020 12:58,11/03/2020 10:27
96,123456111,José Maria,Vendedor,CL001,Loja Matriz,10005,Notebook,Eletrônicos,"2299,9",3199,3,NaN,07/08/2020 13:11,07/08/2020 14:53
97,123456111,José Maria,Vendedor,CL001,Loja Matriz,10020,Impressora,Eletrônicos,"329,9","674,1",3,NaN,29/09/2019 09:05,29/09/2019 12:15
98,123456111,José Maria,Vendedor,CL001,Loja Matriz,10012,Processador de alimentos,Cozinha,110,"189,9",3,NaN,30/09/2019 16:49,01/10/2019 14:55
99,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",3,NaN,08/11/2020 14:32,09/11/2020 09:48

In [10]:
#importando um arq hds h5

df = pd.read_hdf("/content/drive/MyDrive/DADOS/base_vendas.h5")

display(df)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,123456111,José Maria,Vendedor,CL001,Loja Matriz,10017,Cama Box,Casa,"1189,9","1899,5",3,NaN,05/03/2020 12:58,11/03/2020 10:27
96,123456111,José Maria,Vendedor,CL001,Loja Matriz,10005,Notebook,Eletrônicos,"2299,9",3199,3,NaN,07/08/2020 13:11,07/08/2020 14:53
97,123456111,José Maria,Vendedor,CL001,Loja Matriz,10020,Impressora,Eletrônicos,"329,9","674,1",3,NaN,29/09/2019 09:05,29/09/2019 12:15
98,123456111,José Maria,Vendedor,CL001,Loja Matriz,10012,Processador de alimentos,Cozinha,110,"189,9",3,NaN,30/09/2019 16:49,01/10/2019 14:55
99,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",3,NaN,08/11/2020 14:32,09/11/2020 09:48

In [11]:
#importando um arq xml
df = pd.read_xml("/content/drive/MyDrive/DADOS/base_vendas.xml")

display(df)

,index,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,None,28/09/2020 16:19,05/10/2020 16:31
1,1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,None,07/03/2020 12:47,08/03/2020 12:47
2,2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,None,21/04/2019 10:48,23/04/2019 15:55
3,3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,None,07/05/2020 17:59,08/05/2020 14:31
4,4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,"88,9","189,9",3,None,04/11/2019 15:40,05/11/2019 10:40
2996,2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,"59,9","142,4",3,None,24/06/2019 09:04,24/06/2019 10:50
2997,2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,"49,9","95,9",3,None,08/08/2020 14:46,09/08/2020 14:07
2998,2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,"187,9",340,3,None,19/12/2019 09:21,19/12/2019 10:51
2999,2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",3,"0,09",18/03/2019 15:40,23/03/2019 17:52

In [12]:
# importando arquio JSON

df = pd.read_json("/content/drive/MyDrive/DADOS/base_vendas.json")

display(df)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,None,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,None,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,None,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,None,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,"88,9","189,9",3,None,04/11/2019 15:40,05/11/2019 10:40
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,"59,9","142,4",3,None,24/06/2019 09:04,24/06/2019 10:50
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,"49,9","95,9",3,None,08/08/2020 14:46,09/08/2020 14:07
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,"187,9",340,3,None,19/12/2019 09:21,19/12/2019 10:51
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",3,"0,09",18/03/2019 15:40,23/03/2019 17:52

In [13]:
# importando arquivo do excel
#por padrao ler a primeira guia da area e trabalho

df = pd.read_excel("/content/drive/MyDrive/DADOS/Vendas.xlsx")

display(df)

    matricula_funcionario  Nome Funcionario
0               123456111        José Maria
1               123456111        José Maria
2               123456222  Maria das Graças
3               123456333      Jorge Mateus
4               123456555        Marta Cury
5               123456444     Ricardo Lemos
6               123456666   Reginaldo Sodré
7               123456999    Felipe Marinho
8               123456777     Marcos Coelho
9               123456888      Rita Sampaio
10              123457112    Mário Henrique
11              123457111       Pamela Lima
12              123457113       Victor Hugo

In [14]:
# importando arquivo do excel
#para ler uma guia especifica utilizamos um paarametro chamado "sheet-name"e poem entre parentes o nome que eesta

df = pd.read_excel("/content/drive/MyDrive/DADOS/Vendas.xlsx",sheet_name="base_vendas")

display(df)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,210.9,404.1,1,NaN,2020-09-28 16:19:00,2020-10-05 16:31:00
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,109.9,249.9,1,NaN,2020-03-07 12:47:00,2020-03-08 12:47:00
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,699.9,1346.9,1,NaN,2019-04-21 10:48:00,2019-04-23 15:55:00
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,899.9,1676.9,1,NaN,2020-05-07 17:59:00,2020-05-08 14:31:00
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,1,0.05,2019-08-14 16:56:00,2019-08-19 15:52:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,88.9,189.9,3,NaN,2019-11-04 15:40:00,2019-11-05 10:40:00
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,59.9,142.4,3,NaN,2019-06-24 09:04:00,2019-06-24 10:50:00
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,49.9,95.9,3,NaN,2020-08-08 14:46:00,2020-08-09 14:07:00
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,187.9,340.0,3,NaN,2019-12-19 09:21:00,2019-12-19 10:51:00
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,3,0.09,2019-03-18 15:40:00,2019-03-23 17:52:00

In [15]:
#verificando as guias e o arquivo do excel contem
verificacao = pd.ExcelFile("/content/drive/MyDrive/DADOS/Vendas.xlsx")

print(type(verificacao))

#print(verificacao.keys())
#print(verificacao.values())
#print(verificacao.sheet_names)

<class 'pandas.io.excel._base.ExcelFile'>

In [16]:
# importando arquivo em html

tabelas = pd.read_html("/content/drive/MyDrive/DADOS/base_vendas.html")
print(len(tabelas))
print(type(tabelas))
df = tabelas[0]
display(tabelas)

1
<class 'list'>

[    matricula_funcionario Nome Funcionario     Cargo codigo_loja    nome_loja  \
 0               123456111       José Maria  Vendedor       CL001  Loja Matriz
 1               123456111       José Maria  Vendedor       CL001  Loja Matriz
 2               123456111       José Maria  Vendedor       CL001  Loja Matriz
 3               123456111       José Maria  Vendedor       CL001  Loja Matriz
 4               123456111       José Maria  Vendedor       CL001  Loja Matriz
 5               123456111       José Maria  Vendedor       CL001  Loja Matriz
 6               123456111       José Maria  Vendedor       CL001  Loja Matriz
 7               123456111       José Maria  Vendedor       CL001  Loja Matriz
 8               123456111       José Maria  Vendedor       CL001  Loja Matriz
 9               123456111       José Maria  Vendedor       CL001  Loja Matriz
 10              123456111       José Maria  Vendedor       CL001  Loja Matriz
 11              123456111       José Maria  Vendedor       CL001  Loja Matriz
 12              123456111       José Maria  Vendedor       CL001  Loja Matriz
 13              123456111       José Maria  Vendedor       CL001  Loja Matriz
 14              123456111       José Maria  Vendedor       CL001  Loja Matriz
 15              123456111       José Maria  Vendedor       CL001  Loja Matriz
 16              123456111       José Maria  Vendedor       CL001  Loja Matriz
 17              123456111       José Maria  Vendedor       CL001  Loja Matriz
 18              123456111       José Maria  Vendedor       CL001  Loja Matriz
 19              123456111       José Maria  Vendedor       CL001  Loja Matriz

     codigo_produto    descricao_produto         Categoria  preco_custo  \
 0            10013                Fogão  Eletrodomésticos         2109
 1            10018              Colchão              Casa         1099
 2            10014            Geladeira  Eletrodomésticos         6999
 3            10001           Smartphone       Eletrônicos         8999
 4            10004  Máquina Lavar Roupa  Eletrodomésticos         1099
 5            10010  Fritadeira elétrica           Cozinha         1879
 6            10014            Geladeira  Eletrodomésticos         6999
 7            10006      Aspirador de pó              Casa          889
 8            10010  Fritadeira elétrica           Cozinha         1879
 9            10017             Cama Box              Casa        11899
 10           10003            Televisão  Eletrodomésticos        14009
 11           10004  Máquina Lavar Roupa  Eletrodomésticos         1099
 12           10018              Colchão              Casa         1099
 13           10013                Fogão  Eletrodomésticos         2109
 14           10016         Guarda Roupa              Casa         4899
 15           10020           Impressora       Eletrônicos         3299
 16           10017             Cama Box              Casa        11899
 17           10008            Cafeteira           Cozinha         1599
 18           10015           Microondas  Eletrodomésticos          189
 19           10016         Guarda Roupa              Casa         4899

     valor_unitario  quantidade  comissao          dt_venda        dt_entrega
 0             4041           1       NaN  28/09/2020 16:19  05/10/2020 16:31
 1             2499           1       NaN  07/03/2020 12:47  08/03/2020 12:47
 2            13469           1       NaN  21/04/2019 10:48  23/04/2019 15:55
 3            16769           1       NaN  07/05/2020 17:59  08/05/2020 14:31
 4            17091           1       5.0  14/08/2019 16:56  19/08/2019 15:52
 5              340           1       NaN  10/07/2019 15:11  11/07/2019 14:30
 6            13469           1       NaN  26/06/2019 11:03  28/06/2019 13:37
 7             1899           1       NaN  15/03/2020 13:00  16/03/2020 11:15
 8              340           1       NaN  15/08/2020 11:36  15/08/2020 14:22
 9            18995           1       NaN  06/03/2019 13:01  11/03/2019 12:01
 10          227999           1       NaN  11/10/2019 12:44  17/10/2019 14:58
 11           17091           1       5.0  30/10/2019 17:22  03/11/2019 10:21
 12            2499           1       NaN  28/05/2020 16:00  29/05/2020 14:16
 13            4041           1       NaN  30/12/2019 15:07  04/01/2020 16:48
 14             999           1       NaN  16/04/2019 09:22  23/04/2019 10:49
 15            6741           1       NaN  07/09/2019 15:29  08/09/2019 13:00
 16           18995           1       NaN  18/03/2019 09:08  25/03/2019 15:58
 17            2849           1       NaN  28/01/2020 16:40  29/01/2020 11:59
 18            3645           1       NaN  30/10/2020 17:27  31/10/2020 14:16
 19             999           1       NaN  23/10/2020 17:41  30/10/2020 09:27  ]

In [17]:
# conexao com o banco de dados (sqlite)

import sqlite3

conexao = sqlite3.connect("/content/drive/MyDrive/DADOS/vendas.db")

consultas = "SELECT * FROM pedidos"

df = pd.read_sql(consultas,conexao)

display(df)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,123456111,José Maria,Vendedor,CL001,Loja Matriz,10017,Cama Box,Casa,"1189,9","1899,5",3,,05/03/2020 12:58,11/03/2020 10:27
96,123456111,José Maria,Vendedor,CL001,Loja Matriz,10005,Notebook,Eletrônicos,"2299,9",3199,3,,07/08/2020 13:11,07/08/2020 14:53
97,123456111,José Maria,Vendedor,CL001,Loja Matriz,10020,Impressora,Eletrônicos,"329,9","674,1",3,,29/09/2019 09:05,29/09/2019 12:15
98,123456111,José Maria,Vendedor,CL001,Loja Matriz,10012,Processador de alimentos,Cozinha,110,"189,9",3,,30/09/2019 16:49,01/10/2019 14:55
99,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",3,,08/11/2020 14:32,09/11/2020 09:48

In [18]:
# obtendo as tabelas existente em um banco de dados (sqlite)

df = pd.read_sql_query("SELECT name FROM sqlite_schema WHERE type='table'",conexao)

display(df)

      name
0  pedidos

In [19]:
#ANALISE EXPLORATORIA
#importar um arq csv separado por virgula

df_vendas = pd.read_csv("/content/drive/MyDrive/DADOS/base_vendas.csv")

display(df_vendas)
#

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,"88,9","189,9",3,NaN,04/11/2019 15:40,05/11/2019 10:40
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,"59,9","142,4",3,NaN,24/06/2019 09:04,24/06/2019 10:50
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,"49,9","95,9",3,NaN,08/08/2020 14:46,09/08/2020 14:07
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,"187,9",340,3,NaN,19/12/2019 09:21,19/12/2019 10:51
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",3,"0,09",18/03/2019 15:40,23/03/2019 17:52

In [20]:
#ANALISE EXPLORATORIA
#mostrar as priemrias 5 linhas
#df_vendas.head()

#primeiras 15 linhas

#df_vendas.head(15)

#ultimass 5 linhas ou mais linha informar entre ()

#df_vendas.tail(5)

#mostrar estrutura do arq(linha e colunas)

df_vendas.shape

(3000, 14)

In [21]:
#mostrar as informacoes do arq

df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   int64
 1   Nome Funcionario       3000 non-null   object
 2   Cargo                  3000 non-null   object
 3   codigo_loja            3000 non-null   object
 4   nome_loja              3000 non-null   object
 5   codigo_produto         3000 non-null   int64
 6   descricao_produto      3000 non-null   object
 7   Categoria              3000 non-null   object
 8   preco_custo            3000 non-null   object
 9   valor_unitario         3000 non-null   object
 10  quantidade             3000 non-null   int64
 11  comissao               159 non-null    object
 12  dt_venda               3000 non-null   object
 13  dt_entrega             3000 non-null   object
dtypes: int64(3), object(11)
memory usage: 328.3+ KB

In [22]:
#mostrar a descricao doa arquivo (padrao apenas capos numericos)

df_vendas.describe()

       matricula_funcionario  codigo_produto   quantidade
count           3.000000e+03     3000.000000  3000.000000
mean            1.234567e+08    10010.468667     2.453333
std             3.489977e+02        5.772590     1.107955
min             1.234561e+08    10001.000000     1.000000
25%             1.234563e+08    10006.000000     1.000000
50%             1.234567e+08    10011.000000     2.000000
75%             1.234570e+08    10015.000000     3.000000
max             1.234571e+08    10020.000000     4.000000

In [23]:
#mostrar a descricao doa arquivo (campos 'objetc')

df_vendas.describe(include='object')

,Nome Funcionario,Cargo,codigo_loja,nome_loja,descricao_produto,Categoria,preco_custo,valor_unitario,comissao,dt_venda,dt_entrega
count,3000,3000,3000,3000,3000,3000,3000,3000,159,3000,3000
unique,12,1,4,4,20,4,20,19,4,2994,2989
top,José Maria,Vendedor,CL001,Loja Matriz,Aspirador de pó,Casa,"88,9","189,9","0,05",09/07/2019 16:05,09/12/2019 10:12
freq,280,3000,793,793,173,907,173,316,49,2,2

In [24]:
#mostrar a descricao doa arquivo ( todos os campos 'objetc')

df_vendas.describe(include='all')

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
count,3.000000e+03,3000,3000,3000,3000,3000.000000,3000,3000,3000,3000,3000.000000,159,3000,3000
unique,NaN,12,1,4,4,NaN,20,4,20,19,NaN,4,2994,2989
top,NaN,José Maria,Vendedor,CL001,Loja Matriz,NaN,Aspirador de pó,Casa,"88,9","189,9",NaN,"0,05",09/07/2019 16:05,09/12/2019 10:12
freq,NaN,280,3000,793,793,NaN,173,907,173,316,NaN,49,2,2
mean,1.234567e+08,NaN,NaN,NaN,NaN,10010.468667,NaN,NaN,NaN,NaN,2.453333,NaN,NaN,NaN
std,3.489977e+02,NaN,NaN,NaN,NaN,5.772590,NaN,NaN,NaN,NaN,1.107955,NaN,NaN,NaN
min,1.234561e+08,NaN,NaN,NaN,NaN,10001.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN
25%,1.234563e+08,NaN,NaN,NaN,NaN,10006.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN
50%,1.234567e+08,NaN,NaN,NaN,NaN,10011.000000,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN
75%,1.234570e+08,NaN,NaN,NaN,NaN,10015.000000,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN
max,1.234571e+08,NaN,NaN,NaN,NaN,10020.000000,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN

In [25]:
# mostrar os nome das colunas
df_vendas.columns

Index(['matricula_funcionario', 'Nome Funcionario', 'Cargo', 'codigo_loja',
       'nome_loja', 'codigo_produto', 'descricao_produto', 'Categoria',
       'preco_custo', 'valor_unitario', 'quantidade', 'comissao', 'dt_venda',
       'dt_entrega'],
      dtype='object')

In [26]:
#mostrar a qtd de valors unicos por coluna

df_vendas.nunique()

matricula_funcionario      12
Nome Funcionario           12
Cargo                       1
codigo_loja                 4
nome_loja                   4
codigo_produto             20
descricao_produto          20
Categoria                   4
preco_custo                20
valor_unitario             19
quantidade                  4
comissao                    4
dt_venda                 2994
dt_entrega               2989
dtype: int64

In [27]:
# valores unicos do campo "categoria"

df_vendas.Categoria.unique()

array(['Eletrodomésticos', 'Casa', 'Eletrônicos', 'Cozinha'], dtype=object)

In [28]:
#valores unicos do campo 'nome_loja'

df_vendas.nome_loja.unique()

array(['Loja Matriz', 'Filial MG', 'Filial SP', 'Filial ES'], dtype=object)

In [29]:
#valores unicos do campo "nome  funcionario"

df_vendas["Nome Funcionario"].unique()

array(['José Maria', 'Maria das Graças', 'Jorge Mateus', 'Marta Cury',
       'Ricardo Lemos', 'Reginaldo Sodré', 'Felipe Marinho',
       'Marcos Coelho', 'Rita Sampaio', 'Mário Henrique', 'Pamela Lima',
       'Victor Hugo'], dtype=object)

In [30]:
# verificacao de valores nulos

df_vendas.isnull()

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,False,False,False,False,False,False,False,False,False,False,False,True,False,False
2996,False,False,False,False,False,False,False,False,False,False,False,True,False,False
2997,False,False,False,False,False,False,False,False,False,False,False,True,False,False
2998,False,False,False,False,False,False,False,False,False,False,False,True,False,False
2999,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [31]:
#verificacao de linhas duplicatas

df_vendas.duplicated().sum()

np.int64(0)

In [32]:
print(f"Máximo: {df_vendas['quantidade'].max()}")
print(f"Mínimo: {df_vendas['quantidade'].min()}")
print(f"Média: {df_vendas['quantidade'].mean().round(2)}")
print(f"Mediana: {df_vendas['quantidade'].median()}")
print(f"Moda: {df_vendas['quantidade'].mode()}")

Máximo: 4
Mínimo: 1
Média: 2.45
Mediana: 2.0
Moda: 0    1
Name: quantidade, dtype: int64

In [33]:
#importar o aquivo listing.CVS do AIRBNB -SP
df = pd.read_csv("/content/drive/MyDrive/DADOS/meuairbnb.csv")
display(df)

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,4917,Resort Condo Near Av. Paulista,5618,1462506497915065828,Alessandro,Vila Mariana,Vila Mariana,-23.574190,-46.639730,Entire home/apt,633.0,21.0,65,2026-05-07,0.45,1,58,4,NaN
1,54614,Nice area/Cozy flat/ Building rooftop pool,256576,1462513920747223748,Lílian,Se,Santa Cecilia,-23.541530,-46.653620,Entire home/apt,250.0,5.0,209,2026-05-28,1.60,1,67,1,NaN
2,82935,Oscar Freire - Hospital das Clínicas e Nu Bank,451565,1462511917526407290,Thaïs,Pinheiros,Jardim Paulista,-23.556990,-46.674360,Private room,270.0,1.0,109,2026-09-01,0.61,1,360,9,NaN
3,90394,Private Room in Vila Mariana Sao Paulo,490120,1462512168407912455,Egnaldo,Vila Mariana,Vila Mariana,-23.591640,-46.648070,Private room,225.0,1.0,352,2026-09-13,1.88,1,329,29,NaN
4,100549,"Cozy private ensuite, bath, balcony",528205,1462520832717825123,Cristina,Butanta,Morumbi,-23.609030,-46.720770,Private room,308.0,2.0,33,2024-10-10,0.18,8,357,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44075,1774233713252348502,"Metria Tatuapé: Studio Moderno, Garagem e Metrô",8420435,1462767650245408239,Hospedart,Mooca,Tatuape,-23.539929,-46.566494,Entire home/apt,302.0,2.0,0,NaN,NaN,40,171,0,NaN
44076,1774246996160660253,Estúdio moderno e confortável perto do Metro e...,475936415,1774246996849877017,Rennan,Butanta,Butanta,-23.575333,-46.707489,Entire home/apt,328.0,1.0,0,NaN,NaN,1,350,0,NaN
44077,1774264273071085474,Studio aconchegante ao lado do metrô Paraiso,34575412,1462665774641191615,Rafaela,Vila Mariana,Vila Mariana,-23.575886,-46.641482,Entire home/apt,385.0,1.0,0,NaN,NaN,283,344,0,NaN
44078,1774296586556849195,"BEM Moema 1012| Moema, metrô e Shopping Ibirap...",485776541,1648787070566154407,Edgar Milagres,Vila Mariana,Moema,-23.607960,-46.667030,Entire home/apt,300.0,2.0,0,NaN,NaN,20,121,0,NaN
44079,1774310956005895891,Sejam bem-vindos à Casa do Farofa!,167066871,1468618288392559807,Farofa,Butanta,Vila Sonia,-23.585193,-46.726163,Private room,220.0,1.0,0,NaN,NaN,7,358,0,NaN